// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Customer struct {
	ID            string     `json:"id"`
	FirstName     string     `json:"firstName"`
	LastName      string     `json:"lastName"`
	Email         string     `json:"email"`
	TotalPayments float64    `json:"totalPayments"`
	RentalCount   int32      `json:"rentalCount"`
	LastRental    *time.Time `json:"lastRental,omitempty"`
}

type CustomerStats struct {
	Customer     *Customer `json:"customer"`
	TotalSpent   float64   `json:"totalSpent"`
	RentalsCount int32     `json:"rentalsCount"`
}

type Film struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	Description  *string `json:"description,omitempty"`
	Category     string  `json:"category"`
	RentalCount  int32   `json:"rentalCount"`
	TotalRevenue float64 `json:"totalRevenue"`
}

type FilmStats struct {
	Film         *Film   `json:"film"`
	RentalsCount int32   `json:"rentalsCount"`
	TotalRevenue float64 `json:"totalRevenue"`
}

type MonthlyRevenue struct {
	Month   string  `json:"month"`
	Revenue float64 `json:"revenue"`
}

type Payment struct {
	ID          string    `json:"id"`
	Customer    *Customer `json:"customer"`
	Rental      *Rental   `json:"rental"`
	Amount      float64   `json:"amount"`
	PaymentDate time.Time `json:"paymentDate"`
}

type Query struct {
}

type Rental struct {
	ID         string     `json:"id"`
	Customer   *Customer  `json:"customer"`
	Film       *Film      `json:"film"`
	Store      *Store     `json:"store"`
	RentalDate time.Time  `json:"rentalDate"`
	ReturnDate *time.Time `json:"returnDate,omitempty"`
	IsLate     bool       `json:"isLate"`
}

type Store struct {
	ID             string            `json:"id"`
	Address        string            `json:"address"`
	TotalRevenue   float64           `json:"totalRevenue"`
	RentalCount    int32             `json:"rentalCount"`
	MonthlyRevenue []*MonthlyRevenue `json:"monthlyRevenue"`
}

type StoreStats struct {
	Store        *Store  `json:"store"`
	TotalRevenue float64 `json:"totalRevenue"`
	RentalsCount int32   `json:"rentalsCount"`
}
